/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/toweb.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Floar(props) {
  const { nodes, materials } = useGLTF('/toweb.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-27.684, 0, -25.005]}>
        <group position={[4.28, 0, 15.486]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Door004_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door004_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door_Panel.geometry} material={materials['PVC white']} position={[-0.419, 0, -0.171]}>
            <mesh geometry={nodes.Handle009.geometry} material={materials.Inox} position={[0.768, 1, 0]} />
          </mesh>
        </group>
        <group position={[4.229, 0, 6.798]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Door004_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door004_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door_Panel002.geometry} material={materials['PVC white']} position={[-0.419, 0, -0.171]}>
            <mesh geometry={nodes.Handle007.geometry} material={materials.Inox} position={[0.768, 1, 0]} />
          </mesh>
        </group>
        <group position={[5.645, 0, 10.771]}>
          <mesh geometry={nodes.Door_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door_Panel001.geometry} material={materials['PVC white']} position={[-0.419, 0, -0.171]}>
            <mesh geometry={nodes.Handle008.geometry} material={materials.Inox} position={[0.768, 1, 0]} />
          </mesh>
        </group>
        <group position={[6.99, 0, 20.482]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes.Door_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door_Panel003.geometry} material={materials['PVC white']} position={[-0.419, 0, -0.171]}>
            <mesh geometry={nodes.Handle010.geometry} material={materials.Inox} position={[0.768, 1, 0]} />
          </mesh>
        </group>
        <group position={[6.99, 0, 23.898]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes.Door_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door_Panel004.geometry} material={materials['PVC white']} position={[-0.419, 0, -0.171]}>
            <mesh geometry={nodes.Handle011.geometry} material={materials.Inox} position={[0.768, 1, 0]} />
          </mesh>
        </group>
        <group position={[6.99, 0, 38.926]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes.Door001_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door001_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door001_3.geometry} material={materials['Granite grey']} />
          <group position={[-0.519, 0, -0.171]}>
            <mesh geometry={nodes.Door_Panel001_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Door_Panel001_2.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Handle012.geometry} material={materials.Inox} position={[0.968, 1, 0]} />
          </group>
        </group>
        <group position={[2.805, 0, 43.081]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes.Door002_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door002_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door002_3.geometry} material={materials['Granite grey']} />
          <mesh geometry={nodes.Door_Panel006.geometry} material={materials['PVC white']} position={[-0.419, 0, -0.171]}>
            <mesh geometry={nodes.Handle013.geometry} material={materials.Inox} position={[0.768, 1, 0]} />
          </mesh>
        </group>
        <group position={[0, -0.1, 0]}>
          <mesh geometry={nodes.Slab_1.geometry} material={materials['Matt paint white']} />
          <mesh geometry={nodes.Slab_2.geometry} material={materials.Concrete} />
          <mesh geometry={nodes.Slab_3.geometry} material={materials['Stucco white']} />
        </group>
        <mesh geometry={nodes.Stair.geometry} material={materials.Concrete} position={[0.051, -4.124, 55.334]} />
        <group position={[4.079, 0, 0.303]}>
          <mesh geometry={nodes.Wall001_1.geometry} material={materials['Fluffy Velvet']} />
          <mesh geometry={nodes.Wall001_2.geometry} material={materials.Concrete} />
        </group>
        <group position={[14.98, 0, 10.621]}>
          <mesh geometry={nodes.Wall002_1.geometry} material={materials['Fluffy Velvet']} />
          <mesh geometry={nodes.Wall002_2.geometry} material={materials.Concrete} />
        </group>
        <group position={[4.13, 0, 12.621]}>
          <mesh geometry={nodes.Wall003_1.geometry} material={materials['Fluffy Velvet']} />
          <mesh geometry={nodes.Wall003_2.geometry} material={materials.Concrete} />
        </group>
        <group position={[14.98, 0, 40.789]}>
          <mesh geometry={nodes.Wall004_1.geometry} material={materials['Fluffy Velvet']} />
          <mesh geometry={nodes.Wall004_2.geometry} material={materials.Concrete} />
        </group>
        <group position={[13.184, 0, 53.174]}>
          <mesh geometry={nodes.Window_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Handle.geometry} material={materials.Inox} position={[0.576, 0.4, 0]} />
            <mesh geometry={nodes.Window_glass_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel001_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel001_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel001_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel001_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass001_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass001_2.geometry} material={materials.Caoutchouc} />
          </group>
        </group>
        <group position={[5.853, 0, 53.174]}>
          <mesh geometry={nodes.Window_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Handle001.geometry} material={materials.Inox} position={[0.576, 0.4, 0]} />
            <mesh geometry={nodes.Window_glass_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel001_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel001_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel001_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel001_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass001_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass001_2.geometry} material={materials.Caoutchouc} />
          </group>
        </group>
        <group position={[15.13, 0, 50.15]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Window_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Handle002.geometry} material={materials.Inox} position={[0.576, 0.4, 0]} />
            <mesh geometry={nodes.Window_glass_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel001_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel001_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel001_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel001_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass001_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass001_2.geometry} material={materials.Caoutchouc} />
          </group>
        </group>
        <group position={[15.13, 0, 44.008]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Window_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Handle003.geometry} material={materials.Inox} position={[0.576, 0.4, 0]} />
            <mesh geometry={nodes.Window_glass_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel001_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel001_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel001_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel001_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass001_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass001_2.geometry} material={materials.Caoutchouc} />
          </group>
        </group>
        <group position={[15.13, 0, 36.946]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Window001_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window001_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window001_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window001_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.123]}>
            <mesh geometry={nodes.Window_Panel002_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel002_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel002_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel002_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass002_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass002_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[-0.6, 1.52, -0.062]}>
            <mesh geometry={nodes.Window_Panel003_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel003_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel003_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel003_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass003_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass003_2.geometry} material={materials.Caoutchouc} />
          </group>
        </group>
        <group position={[15.13, 0, 27.03]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Window002_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window002_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window002_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window002_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel004_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel004_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel004_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel004_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Handle004.geometry} material={materials.Inox} position={[0.576, 0.4, 0]} />
            <mesh geometry={nodes.Window_glass004_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass004_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel005_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel005_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel005_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel005_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass005_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass005_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[-0.6, 1.8, -0.122]}>
            <mesh geometry={nodes.Window_Panel006_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel006_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel006_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel006_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass006_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass006_2.geometry} material={materials.Inox} />
          </group>
        </group>
        <group position={[15.13, 0, 16.249]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Window002_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window002_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window002_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window002_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel004_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel004_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel004_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel004_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Handle005.geometry} material={materials.Inox} position={[0.576, 0.4, 0]} />
            <mesh geometry={nodes.Window_glass004_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass004_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel005_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel005_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel005_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel005_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass005_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass005_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[-0.6, 1.8, -0.122]}>
            <mesh geometry={nodes.Window_Panel006_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel006_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel006_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel006_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass006_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass006_2.geometry} material={materials.Inox} />
          </group>
        </group>
        <group position={[10.695, 0, 0.157]} rotation={[-Math.PI, 0.001, -Math.PI]}>
          <mesh geometry={nodes.Window002_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window002_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window002_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window002_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel004_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel004_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel004_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel004_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Handle006.geometry} material={materials.Inox} position={[0.576, 0.4, 0]} />
            <mesh geometry={nodes.Window_glass004_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass004_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel005_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel005_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel005_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel005_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass005_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass005_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[-0.6, 1.8, -0.122]}>
            <mesh geometry={nodes.Window_Panel006_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel006_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel006_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel006_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass006_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass006_2.geometry} material={materials.Inox} />
          </group>
        </group>
        <group position={[2.787, 0, 0.152]} rotation={[-Math.PI, 0.001, -Math.PI]}>
          <mesh geometry={nodes.Window003_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window003_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window003_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window003_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel007_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel007_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel007_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel007_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass007_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass007_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[-0.6, 1.52, -0.063]}>
            <mesh geometry={nodes.Window_Panel008_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel008_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel008_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel008_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass008_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass008_2.geometry} material={materials.Caoutchouc} />
          </group>
        </group>
        <group position={[1.665, 0, 21.092]}>
          <mesh geometry={nodes.Window003_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window003_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window003_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window003_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel007_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel007_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel007_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel007_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass007_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass007_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[-0.6, 1.52, -0.063]}>
            <mesh geometry={nodes.Window_Panel008_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel008_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel008_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel008_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass008_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass008_2.geometry} material={materials.Caoutchouc} />
          </group>
        </group>
        <mesh geometry={nodes.Wall_1.geometry} material={materials['Fluffy Velvet']} />
        <mesh geometry={nodes.Wall_2.geometry} material={materials.Concrete} />
      </group>
      <group position={[-27.634, 0, -25.005]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <group position={[5.645, 0, 10.771]}>
          <mesh geometry={nodes.Door003_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door003_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door_Panel007.geometry} material={materials['PVC white']} position={[-0.419, 0, -0.171]}>
            <mesh geometry={nodes.Handle021.geometry} material={materials.Inox} position={[0.768, 1, 0]} />
          </mesh>
        </group>
        <group position={[6.99, 0, 20.482]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes.Door003_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door003_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door_Panel008.geometry} material={materials['PVC white']} position={[-0.419, 0, -0.171]}>
            <mesh geometry={nodes.Handle022.geometry} material={materials.Inox} position={[0.768, 1, 0]} />
          </mesh>
        </group>
        <group position={[6.99, 0, 23.898]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes.Door003_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door003_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door_Panel009.geometry} material={materials['PVC white']} position={[-0.419, 0, -0.171]}>
            <mesh geometry={nodes.Handle023.geometry} material={materials.Inox} position={[0.768, 1, 0]} />
          </mesh>
        </group>
        <group position={[6.99, 0, 38.926]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes.Door005_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door005_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door005_3.geometry} material={materials['Granite grey']} />
          <group position={[-0.519, 0, -0.171]}>
            <mesh geometry={nodes.Door_Panel005_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Door_Panel005_2.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Handle024.geometry} material={materials.Inox} position={[0.968, 1, 0]} />
          </group>
        </group>
        <group position={[2.805, 0, 43.081]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes.Door006_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door006_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door006_3.geometry} material={materials['Granite grey']} />
          <mesh geometry={nodes.Door_Panel011.geometry} material={materials['PVC white']} position={[-0.419, 0, -0.171]}>
            <mesh geometry={nodes.Handle025.geometry} material={materials.Inox} position={[0.768, 1, 0]} />
          </mesh>
        </group>
        <group position={[4.229, 0, 6.798]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Door007_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door007_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door_Panel012.geometry} material={materials['PVC white']} position={[-0.419, 0, -0.171]}>
            <mesh geometry={nodes.Handle026.geometry} material={materials.Inox} position={[0.768, 1, 0]} />
          </mesh>
        </group>
        <group position={[4.28, 0, 15.486]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Door007_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door007_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door_Panel013.geometry} material={materials['PVC white']} position={[-0.419, 0, -0.171]}>
            <mesh geometry={nodes.Handle027.geometry} material={materials.Inox} position={[0.768, 1, 0]} />
          </mesh>
        </group>
        <group position={[0, -0.1, 0]}>
          <mesh geometry={nodes.Slab001_1.geometry} material={materials['Matt paint white']} />
          <mesh geometry={nodes.Slab001_2.geometry} material={materials.Concrete} />
          <mesh geometry={nodes.Slab001_3.geometry} material={materials['Stucco white']} />
        </group>
        <group position={[4.079, 0, 0.303]}>
          <mesh geometry={nodes.Wall006_1.geometry} material={materials['Fluffy Velvet']} />
          <mesh geometry={nodes.Wall006_2.geometry} material={materials.Concrete} />
        </group>
        <group position={[14.98, 0, 10.621]}>
          <mesh geometry={nodes.Wall007_1.geometry} material={materials['Fluffy Velvet']} />
          <mesh geometry={nodes.Wall007_2.geometry} material={materials.Concrete} />
        </group>
        <group position={[4.13, 0, 12.621]}>
          <mesh geometry={nodes.Wall008_1.geometry} material={materials['Fluffy Velvet']} />
          <mesh geometry={nodes.Wall008_2.geometry} material={materials.Concrete} />
        </group>
        <group position={[14.98, 0, 40.789]}>
          <mesh geometry={nodes.Wall009_1.geometry} material={materials['Fluffy Velvet']} />
          <mesh geometry={nodes.Wall009_2.geometry} material={materials.Concrete} />
        </group>
        <group position={[13.184, 0, 53.174]}>
          <mesh geometry={nodes.Window004_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window004_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window004_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window004_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel009_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel009_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel009_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel009_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Handle014.geometry} material={materials.Inox} position={[0.576, 0.4, 0]} />
            <mesh geometry={nodes.Window_glass009_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass009_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel010_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel010_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel010_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel010_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass010_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass010_2.geometry} material={materials.Caoutchouc} />
          </group>
        </group>
        <group position={[5.853, 0, 53.174]}>
          <mesh geometry={nodes.Window004_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window004_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window004_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window004_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel009_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel009_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel009_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel009_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Handle015.geometry} material={materials.Inox} position={[0.576, 0.4, 0]} />
            <mesh geometry={nodes.Window_glass009_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass009_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel010_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel010_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel010_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel010_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass010_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass010_2.geometry} material={materials.Caoutchouc} />
          </group>
        </group>
        <group position={[15.13, 0, 50.15]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Window004_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window004_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window004_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window004_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel009_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel009_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel009_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel009_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Handle016.geometry} material={materials.Inox} position={[0.576, 0.4, 0]} />
            <mesh geometry={nodes.Window_glass009_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass009_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel010_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel010_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel010_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel010_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass010_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass010_2.geometry} material={materials.Caoutchouc} />
          </group>
        </group>
        <group position={[15.13, 0, 44.008]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Window004_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window004_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window004_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window004_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel009_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel009_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel009_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel009_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Handle017.geometry} material={materials.Inox} position={[0.576, 0.4, 0]} />
            <mesh geometry={nodes.Window_glass009_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass009_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel010_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel010_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel010_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel010_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass010_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass010_2.geometry} material={materials.Caoutchouc} />
          </group>
        </group>
        <group position={[15.13, 0, 36.946]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Window005_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window005_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window005_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window005_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.123]}>
            <mesh geometry={nodes.Window_Panel011_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel011_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel011_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel011_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass011_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass011_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[-0.6, 1.52, -0.062]}>
            <mesh geometry={nodes.Window_Panel012_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel012_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel012_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel012_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass012_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass012_2.geometry} material={materials.Caoutchouc} />
          </group>
        </group>
        <group position={[15.13, 0, 27.03]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Window006_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window006_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window006_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window006_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel013_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel013_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel013_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel013_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Handle018.geometry} material={materials.Inox} position={[0.576, 0.4, 0]} />
            <mesh geometry={nodes.Window_glass013_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass013_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel014_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel014_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel014_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel014_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass014_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass014_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[-0.6, 1.8, -0.122]}>
            <mesh geometry={nodes.Window_Panel015_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel015_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel015_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel015_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass015_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass015_2.geometry} material={materials.Inox} />
          </group>
        </group>
        <group position={[15.13, 0, 16.249]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Window006_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window006_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window006_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window006_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel013_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel013_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel013_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel013_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Handle019.geometry} material={materials.Inox} position={[0.576, 0.4, 0]} />
            <mesh geometry={nodes.Window_glass013_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass013_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel014_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel014_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel014_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel014_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass014_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass014_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[-0.6, 1.8, -0.122]}>
            <mesh geometry={nodes.Window_Panel015_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel015_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel015_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel015_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass015_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass015_2.geometry} material={materials.Inox} />
          </group>
        </group>
        <group position={[10.695, 0, 0.157]} rotation={[-Math.PI, 0.001, -Math.PI]}>
          <mesh geometry={nodes.Window006_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window006_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window006_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window006_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel013_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel013_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel013_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel013_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Handle020.geometry} material={materials.Inox} position={[0.576, 0.4, 0]} />
            <mesh geometry={nodes.Window_glass013_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass013_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel014_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel014_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel014_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel014_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass014_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass014_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[-0.6, 1.8, -0.122]}>
            <mesh geometry={nodes.Window_Panel015_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel015_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel015_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel015_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass015_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass015_2.geometry} material={materials.Inox} />
          </group>
        </group>
        <group position={[2.787, 0, 0.152]} rotation={[-Math.PI, 0.001, -Math.PI]}>
          <mesh geometry={nodes.Window007_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window007_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window007_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window007_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.123]}>
            <mesh geometry={nodes.Window_Panel016_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel016_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel016_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel016_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass016_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass016_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[-0.6, 1.52, -0.063]}>
            <mesh geometry={nodes.Window_Panel017_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel017_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel017_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel017_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass017_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass017_2.geometry} material={materials.Caoutchouc} />
          </group>
        </group>
        <group position={[1.665, 0, 21.092]}>
          <mesh geometry={nodes.Window007_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window007_2.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Window007_3.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Window007_4.geometry} material={materials['Granite grey']} />
          <group position={[-0.6, 1, -0.122]}>
            <mesh geometry={nodes.Window_Panel016_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel016_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel016_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel016_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass016_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass016_2.geometry} material={materials.Caoutchouc} />
          </group>
          <group position={[-0.6, 1.52, -0.063]}>
            <mesh geometry={nodes.Window_Panel017_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel017_2.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Window_Panel017_3.geometry} material={materials.Inox} />
            <mesh geometry={nodes.Window_Panel017_4.geometry} material={materials.Caoutchouc} />
            <mesh geometry={nodes.Window_glass017_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Window_glass017_2.geometry} material={materials.Caoutchouc} />
          </group>
        </group>
        <mesh geometry={nodes.Wall005_1.geometry} material={materials['Fluffy Velvet']} />
        <mesh geometry={nodes.Wall005_2.geometry} material={materials.Concrete} />
      </group>
      <group position={[-25.221, 0, 22.012]}>
        <group position={[-2.435, 0, 0.15]}>
          <mesh geometry={nodes.Door008_1.geometry} material={materials['PVC white']} />
          <mesh geometry={nodes.Door008_2.geometry} material={materials.Aluminium} />
          <mesh geometry={nodes.Door008_3.geometry} material={materials['Granite grey']} />
          <group position={[-2.304, 0, -0.171]} rotation={[0, 1.239, 0]}>
            <mesh geometry={nodes.Door_Panel008_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Door_Panel008_2.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Handle028.geometry} material={materials.Inox} position={[2.233, 1.01, 0]} />
          </group>
          <group position={[2.304, 0, -0.171]}>
            <mesh geometry={nodes.Door_Panel009_1.geometry} material={materials['PVC white']} />
            <mesh geometry={nodes.Door_Panel009_2.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Handle029.geometry} material={materials.Inox} position={[-2.233, 1.01, 0]} />
          </group>
        </group>
        <group position={[0.345, 0, 0]}>
          <mesh geometry={nodes.Wall010_1.geometry} material={materials['Marble Generator']} />
          <mesh geometry={nodes.Wall010_2.geometry} material={materials.Concrete} />
        </group>
      </group>
      <group position={[-27.221, 0, 22.112]}>
        <group position={[1.616, 0, -10.474]}>
          <mesh geometry={nodes.Stair001_1.geometry} material={materials['Matt paint white']} />
          <mesh geometry={nodes.Stair001_2.geometry} material={materials['Granite grey']} />
          <mesh geometry={nodes.Stair001_3.geometry} material={materials.Inox} />
          <mesh geometry={nodes.Stair001_4.geometry} material={materials.Glass} />
        </group>
      </group>
      <group position={[-25.221, -0.3, 26.012]}>
        <group position={[-5.064, 0.3, -10.322]}>
          <mesh geometry={nodes.Slab002_1.geometry} material={materials['Matt paint white']} />
          <mesh geometry={nodes.Slab002_2.geometry} material={materials.Concrete} />
          <mesh geometry={nodes.Slab002_3.geometry} material={materials['Stucco white']} />
        </group>
        <group position={[-6.869, 0.3, -30.075]}>
          <mesh geometry={nodes.Slab003_1.geometry} material={materials['Matt paint white']} />
          <mesh geometry={nodes.Slab003_2.geometry} material={materials.Concrete} />
          <mesh geometry={nodes.Slab003_3.geometry} material={materials['Stucco white']} />
        </group>
      </group>
      <group position={[-12.555, 0.15, 7.318]}>
        <group position={[-0.05, -0.169, 0]}>
          <mesh geometry={nodes.Wall011_1.geometry} material={materials['Fluffy Velvet']} />
          <mesh geometry={nodes.Wall011_2.geometry} material={materials.Concrete} />
        </group>
        <group position={[-0.05, -0.169, -10.986]}>
          <mesh geometry={nodes.Wall012_1.geometry} material={materials['Fluffy Velvet']} />
          <mesh geometry={nodes.Wall012_2.geometry} material={materials.Concrete} />
        </group>
        <group position={[-22.19, -0.169, -10.986]}>
          <mesh geometry={nodes.Wall013_1.geometry} material={materials['Fluffy Velvet']} />
          <mesh geometry={nodes.Wall013_2.geometry} material={materials.Concrete} />
        </group>
        <group position={[-22.19, -0.169, -0.34]}>
          <mesh geometry={nodes.Wall014_1.geometry} material={materials['Fluffy Velvet']} />
          <mesh geometry={nodes.Wall014_2.geometry} material={materials.Concrete} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/toweb.glb')
